exports_files([
    "mirror_paths.py",
    "expand_globs.py",
    "get_dll_from_import_lib.py",
])

filegroup(
    name = "python_sources",
    srcs = [
        "expand_globs.py",
        "get_dll_from_import_lib.py",
        "mirror_paths.py",
    ],
    tags = ["lint-with-ruff"],
    visibility = ["//visibility:public"],
)
